{
 "title": "Maily Service Mesh Dashboard",
 "tags": [
  "istio",
  "service-mesh",
  "maily"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(istio_requests_total, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Service Mesh Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_requests_total{namespace=~\"$namespace\",reporter=\"destination\"}) by (destination_service)",
     "legendFormat": "{{destination_service}}"
    }
   ]
  },
  {
   "title": "Error Rate by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=~\"$namespace\",reporter=\"destination\",response_code!~\"2..\"}[5m])) by (destination_service)",
     "legendFormat": "{{destination_service}}"
    }
   ]
  },
  { "title": "Service Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "P95 Latency by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{namespace=~\"$namespace\",reporter=\"destination\"}[5m])) by (destination_service, le))",
     "legendFormat": "{{destination_service}}"
    }
   ]
  },
  {
   "title": "Request Rate by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=~\"$namespace\",reporter=\"destination\"}[5m])) by (destination_service)",
     "legendFormat": "{{destination_service}}"
    }
   ]
  },
  { "title": "Circuit Breaker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Circuit Breaker - Connections Open",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_cx_open{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Circuit Breaker - Pending Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_rq_pending_open{namespace=~\"$namespace\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "mTLS & Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "mTLS vs non-mTLS Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_requests_total{namespace=~\"$namespace\",reporter=\"destination\",connection_security_policy=\"mutual_tls\"}) by (destination_service)",
     "legendFormat": "mTLS: {{destination_service}}"
    },
    {
     "expr": "sum(istio_requests_total{namespace=~\"$namespace\",reporter=\"destination\",connection_security_policy!=\"mutual_tls\"}) by (destination_service)",
     "legendFormat": "non-mTLS: {{destination_service}}"
    }
   ]
  },
  {
   "title": "Error Responses by Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(istio_requests_total{namespace=~\"$namespace\",reporter=\"destination\",response_code!=\"200\"}) by (destination_service, response_code)"
    }
   ]
  }
 ]
}