apiVersion: v1
kind: ConfigMap
metadata:
  name: maily-prometheus-config
  namespace: maily-production
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    rule_files:
      - /etc/prometheus/rules/*.yml
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093
    scrape_configs:
      - job_name: 'api'
        metrics_path: '/metrics'
        static_configs:
        - targets: ['maily-ai-service:80']
      - job_name: 'redis'
        static_configs:
        - targets: ['redis-master:6379']
