global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'maily_backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^http_.*'
        action: keep

  - job_name: 'maily_database'
    static_configs:
      - targets: ['localhost:9187']  # PostgreSQL exporter
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^pg_.*'
        action: keep

  - job_name: 'maily_redis'
    static_configs:
      - targets: ['localhost:9121']  # Redis exporter
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^redis_.*'
        action: keep

  - job_name: 'maily_node'
    static_configs:
      - targets: ['localhost:9100']  # Node exporter
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^(node_cpu|node_memory|node_disk|node_network).*'
        action: keep

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - 'alert.rules.yml'
