apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: maily-production
data:
  alert-rules.yml: |
    groups:
    - name: maily-alerts
      rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute."
      
      - alert: HighErrorRate
        expr: sum(rate(api_request_total{status_code=~"5.."}[5m])) / sum(rate(api_request_total[5m])) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 2 minutes."
      
      - alert: PodCrashLooping
        expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Pod {{ $labels.pod }} is crash looping"
          description: "Pod {{ $labels.pod }} has restarted more than 5 times in the last hour."
