# Standardized Docker Compose configuration for local development
# 
# This is a symlink to the standardized configuration in docker/compose/docker-compose.yml
# For detailed configuration, please see that file.

# Import the standardized Docker Compose configuration
include:
  - path: ./docker/compose/docker-compose.yml