global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: api-service
    metrics_path: /metrics
    static_configs:
      - targets: ['api-service:8000']
        labels:
          service: api
          environment: ${ENVIRONMENT}

  - job_name: ai-service
    metrics_path: /metrics
    static_configs:
      - targets: ['ai-service:8080']
        labels:
          service: ai
          environment: ${ENVIRONMENT}

  - job_name: email-service
    metrics_path: /metrics
    static_configs:
      - targets: ['email-service:3000']
        labels:
          service: email
          environment: ${ENVIRONMENT}

  - job_name: web-service
    metrics_path: /metrics
    static_configs:
      - targets: ['web-service:3000']
        labels:
          service: web
          environment: ${ENVIRONMENT}

  - job_name: workers
    metrics_path: /metrics
    static_configs:
      - targets: ['workers:8888']
        labels:
          service: workers
          environment: ${ENVIRONMENT}

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: redis
          environment: ${ENVIRONMENT}

  - job_name: postgres-exporter
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: postgres
          environment: ${ENVIRONMENT}

  - job_name: rabbitmq-exporter
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
        labels:
          service: rabbitmq
          environment: ${ENVIRONMENT}