apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ai-service
  labels:
    app: ai-service
    part-of: maily
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: ai-service
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ai-service
  labels:
    app: ai-service
    part-of: maily
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.aiService.replicas }}
  selector:
    matchLabels:
      app: ai-service
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: ai-service
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: ai-service
        image: "{{ .Values.aiService.image.repository }}:{{ .Values.aiService.image.tag }}"
        imagePullPolicy: {{ .Values.aiService.image.pullPolicy }}
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LOG_LEVEL
          value: "{{ .Values.aiService.logLevel }}"
        - name: REDIS_URL
          value: redis://{{ .Release.Name }}-redis:6379
        - name: API_URL
          value: http://{{ .Release.Name }}-backend:80
        - name: WEBSOCKET_ENABLED
          value: "{{ .Values.aiService.websocket.enabled }}"
        {{- if .Values.aiService.env }}
        {{- range $key, $value := .Values.aiService.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.aiService.resources.limits.cpu }}
            memory: {{ .Values.aiService.resources.limits.memory }}
          requests:
            cpu: {{ .Values.aiService.resources.requests.cpu }}
            memory: {{ .Values.aiService.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      {{- with .Values.aiService.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.aiService.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.aiService.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if .Values.aiService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-ai-service
  labels:
    app: ai-service
    part-of: maily
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-ai-service
  minReplicas: {{ .Values.aiService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.aiService.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.aiService.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.aiService.autoscaling.targetMemoryUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
{{- end }}