{{- if .Values.autoscaling.enabled }}
# Frontend Autoscaling
{{- if .Values.frontend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "maily.fullname" . }}-frontend
  labels:
    {{- include "maily.labels" . | nindent 4 }}
    component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "maily.fullname" . }}-frontend
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
  {{- if .Values.frontend.autoscaling.custom }}
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: {{ .Values.frontend.autoscaling.requestsPerSecondTarget }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 20
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
{{- end }}

# Backend Autoscaling
{{- if .Values.backend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "maily.fullname" . }}-backend
  labels:
    {{- include "maily.labels" . | nindent 4 }}
    component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "maily.fullname" . }}-backend
  minReplicas: {{ .Values.backend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backend.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.backend.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.backend.autoscaling.targetMemoryUtilizationPercentage }}
  {{- if .Values.backend.autoscaling.custom }}
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: {{ .Values.backend.autoscaling.requestsPerSecondTarget }}
  - type: Object
    object:
      metric:
        name: rabbitmq_queue_length
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "maily.fullname" . }}-rabbitmq
      target:
        type: Value
        value: {{ .Values.backend.autoscaling.queueLengthTarget }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 20
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
{{- end }}

# Worker Autoscaling
{{- if .Values.worker.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "maily.fullname" . }}-worker
  labels:
    {{- include "maily.labels" . | nindent 4 }}
    component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "maily.fullname" . }}-worker
  minReplicas: {{ .Values.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.worker.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.worker.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.worker.autoscaling.targetMemoryUtilizationPercentage }}
  {{- if .Values.worker.autoscaling.custom }}
  - type: Object
    object:
      metric:
        name: rabbitmq_queue_length
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "maily.fullname" . }}-rabbitmq
      target:
        type: Value
        value: {{ .Values.worker.autoscaling.queueLengthTarget }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 20
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
{{- end }}

# API Edge Caching Autoscaling
{{- if .Values.apiEdgeCaching.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "maily.fullname" . }}-api-edge-cache
  labels:
    {{- include "maily.labels" . | nindent 4 }}
    component: api-edge-cache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "maily.fullname" . }}-api-edge-cache
  minReplicas: {{ .Values.apiEdgeCaching.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiEdgeCaching.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.apiEdgeCaching.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.apiEdgeCaching.autoscaling.targetMemoryUtilizationPercentage }}
  {{- if .Values.apiEdgeCaching.autoscaling.custom }}
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: {{ .Values.apiEdgeCaching.autoscaling.requestsPerSecondTarget }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 20
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
{{- end }}

# WAF Autoscaling
{{- if and .Values.security.enabled .Values.security.waf.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "maily.fullname" . }}-waf
  labels:
    {{- include "maily.labels" . | nindent 4 }}
    component: security
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "maily.fullname" . }}-waf
  minReplicas: {{ .Values.security.waf.autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ .Values.security.waf.autoscaling.maxReplicas | default 5 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.security.waf.autoscaling.targetCPUUtilizationPercentage | default 70 }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.security.waf.autoscaling.targetMemoryUtilizationPercentage | default 70 }}
  {{- if .Values.security.waf.autoscaling.custom }}
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: {{ .Values.security.waf.autoscaling.requestsPerSecondTarget | default 100 }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 20
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
{{- end }}
{{- end }}
