{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-secrets
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: maily
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
