groups:
- name: maily-infrastructure
  rules:
  - alert: HighCpuUsage
    expr: avg(container_cpu_usage_seconds_total{namespace="maily-production"}) by (pod) > 0.85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.pod }}"
      description: "Pod {{ $labels.pod }} has high CPU usage (> 85%) for more than 5 minutes."

  - alert: HighMemoryUsage
    expr: avg(container_memory_usage_bytes{namespace="maily-production"}) by (pod) / avg(container_spec_memory_limit_bytes{namespace="maily-production"}) by (pod) > 0.85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.pod }}"
      description: "Pod {{ $labels.pod }} has high memory usage (> 85%) for more than 5 minutes."

  - alert: PodCrashLooping
    expr: rate(kube_pod_container_status_restarts_total{namespace="maily-production"}[15m]) * 60 > 0.5
    for: 15m
    labels:
      severity: critical
    annotations:
      summary: "Pod {{ $labels.pod }} is crash looping"
      description: "Pod {{ $labels.pod }} is restarting more than 0.5 times per minute over the last 15 minutes."

  - alert: PodNotReady
    expr: sum by (pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed", namespace="maily-production"}) > 0
    for: 15m
    labels:
      severity: critical
    annotations:
      summary: "Pod {{ $labels.pod }} is not ready"
      description: "Pod {{ $labels.pod }} has been in a non-ready state for more than 15 minutes."

  - alert: NodeHighCpuUsage
    expr: instance:node_cpu_utilisation:rate5m > 0.8
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Node {{ $labels.instance }} CPU usage is high"
      description: "Node {{ $labels.instance }} CPU usage is above 80% for more than 10 minutes."

  - alert: NodeHighMemoryUsage
    expr: node:node_memory_utilisation: > 0.85
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Node {{ $labels.instance }} memory usage is high"
      description: "Node {{ $labels.instance }} memory usage is above 85% for more than 10 minutes."

  - alert: NodeDiskPressure
    expr: kube_node_status_condition{condition="DiskPressure", status="true"} == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Node {{ $labels.node }} is under disk pressure"
      description: "Node {{ $labels.node }} is under disk pressure for more than 5 minutes."

  - alert: ContainerWaiting
    expr: sum by (namespace, pod, container) (kube_pod_container_status_waiting_reason{namespace="maily-production"}) > 0
    for: 1h
    labels:
      severity: warning
    annotations:
      summary: "Container {{ $labels.container }} in pod {{ $labels.pod }} is waiting"
      description: "Container {{ $labels.container }} in pod {{ $labels.pod }} has been waiting for more than 1 hour."

  - alert: KubernetesJobFailed
    expr: kube_job_status_failed{namespace="maily-production"} > 0
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Job {{ $labels.job_name }} has failed"
      description: "Job {{ $labels.job_name }} has failed execution."

  - alert: KubernetesCronJobsFailed
    expr: time() - kube_cronjob_status_last_schedule_time{namespace="maily-production"} > 3600
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "CronJob {{ $labels.cronjob }} has not run recently"
      description: "CronJob {{ $labels.cronjob }} has not run in the last hour."
