apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: monitoring
type: Opaque
stringData:
  # Default password for the elastic user (should be changed in production)
  password: "changeme-in-production"
  # Password for kibana_system user
  kibana-password: "changeme-in-production"
  # Password for logstash_system user
  logstash-password: "changeme-in-production"
  # Password for beats_system user
  beats-password: "changeme-in-production"
  # Password for remote monitoring user
  remote-monitoring-password: "changeme-in-production"
