apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/helm-charts
    name: loki-stack
    version: 2.6.4
  values:
    loki:
      enabled: true
      persistence:
        enabled: true
        storageClassName: gp2
        size: 50Gi
      config:
        auth_enabled: false
        ingester:
          chunk_idle_period: 3m
          chunk_block_size: 262144
          chunk_retain_period: 1m
          max_transfer_retries: 0
          lifecycler:
            ring:
              kvstore:
                store: inmemory
              replication_factor: 1
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
        schema_config:
          configs:
          - from: 2020-10-24
            store: boltdb-shipper
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
        server:
          http_listen_port: 3100
        storage_config:
          boltdb_shipper:
            active_index_directory: /data/loki/boltdb-shipper-active
            cache_location: /data/loki/boltdb-shipper-cache
            cache_ttl: 24h
            shared_store: filesystem
          filesystem:
            directory: /data/loki/chunks
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: false
          retention_period: 0s
    promtail:
      enabled: true
      config:
        lokiAddress: http://loki:3100/loki/api/v1/push
        snippets:
          pipelineStages:
            - docker: {}
            - match:
                selector: '{app="maily-api"}'
                stages:
                - json:
                    expressions:
                      level: level
                      message: message
                      timestamp: timestamp
                - labels:
                    level:
                - timestamp:
                    source: timestamp
                    format: RFC3339Nano
            - match:
                selector: '{app="maily-frontend"}'
                stages:
                - json:
                    expressions:
                      level: level
                      message: message
                      timestamp: timestamp
                - labels:
                    level:
                - timestamp:
                    source: timestamp
                    format: RFC3339Nano
            - match:
                selector: '{app="maily-worker"}'
                stages:
                - json:
                    expressions:
                      level: level
                      message: message
                      timestamp: timestamp
                - labels:
                    level:
                - timestamp:
                    source: timestamp
                    format: RFC3339Nano
      serviceMonitor:
        enabled: true
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
    filebeat:
      enabled: false
    logstash:
      enabled: false
