apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 34.10.0
  values:
    prometheus:
      prometheusSpec:
        retention: 15d
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: gp2
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        additionalScrapeConfigs:
          - job_name: 'maily-api'
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - maily
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_label_app]
                regex: maily-api
                action: keep
              - source_labels: [__meta_kubernetes_endpoint_port_name]
                regex: metrics
                action: keep
          - job_name: 'maily-frontend'
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - maily
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_label_app]
                regex: maily-frontend
                action: keep
              - source_labels: [__meta_kubernetes_endpoint_port_name]
                regex: metrics
                action: keep
          - job_name: 'maily-worker'
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - maily
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_label_app]
                regex: maily-worker
                action: keep
              - source_labels: [__meta_kubernetes_endpoint_port_name]
                regex: metrics
                action: keep
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: gp2
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
        resources:
          requests:
            memory: 200Mi
            cpu: 100m
          limits:
            memory: 400Mi
            cpu: 200m
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['job', 'alertname', 'severity']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: 'slack'
          routes:
          - match:
              alertname: Watchdog
            receiver: 'null'
          - match:
              severity: critical
            receiver: 'pagerduty'
        receivers:
        - name: 'null'
        - name: 'slack'
          slack_configs:
          - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'
            channel: '#maily-alerts'
            send_resolved: true
            title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Alert'
            text: >-
              {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }}
                *Description:* {{ .Annotations.description }}
                *Severity:* {{ .Labels.severity }}
                *Details:*
                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
              {{ end }}
        - name: 'pagerduty'
          pagerduty_configs:
          - service_key: 'your-pagerduty-service-key'
            send_resolved: true
    grafana:
      enabled: true
      adminPassword: "admin-password-to-be-replaced"
      persistence:
        enabled: true
        storageClassName: gp2
        size: 10Gi
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'maily'
            orgId: 1
            folder: 'Maily'
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/maily
      dashboards:
        maily:
          maily-api-dashboard:
            json: |
              {
                "annotations": {
                  "list": [
                    {
                      "builtIn": 1,
                      "datasource": "-- Grafana --",
                      "enable": true,
                      "hide": true,
                      "iconColor": "rgba(0, 211, 255, 1)",
                      "name": "Annotations & Alerts",
                      "type": "dashboard"
                    }
                  ]
                },
                "editable": true,
                "gnetId": null,
                "graphTooltip": 0,
                "id": 1,
                "links": [],
                "panels": [
                  {
                    "aliasColors": {},
                    "bars": false,
                    "dashLength": 10,
                    "dashes": false,
                    "datasource": "Prometheus",
                    "fieldConfig": {
                      "defaults": {
                        "custom": {}
                      },
                      "overrides": []
                    },
                    "fill": 1,
                    "fillGradient": 0,
                    "gridPos": {
                      "h": 8,
                      "w": 12,
                      "x": 0,
                      "y": 0
                    },
                    "hiddenSeries": false,
                    "id": 2,
                    "legend": {
                      "avg": false,
                      "current": false,
                      "max": false,
                      "min": false,
                      "show": true,
                      "total": false,
                      "values": false
                    },
                    "lines": true,
                    "linewidth": 1,
                    "nullPointMode": "null",
                    "options": {
                      "alertThreshold": true
                    },
                    "percentage": false,
                    "pluginVersion": "7.2.0",
                    "pointradius": 2,
                    "points": false,
                    "renderer": "flot",
                    "seriesOverrides": [],
                    "spaceLength": 10,
                    "stack": false,
                    "steppedLine": false,
                    "targets": [
                      {
                        "expr": "sum(rate(http_requests_total{job=\"maily-api\"}[5m])) by (status_code)",
                        "interval": "",
                        "legendFormat": "{{status_code}}",
                        "refId": "A"
                      }
                    ],
                    "thresholds": [],
                    "timeFrom": null,
                    "timeRegions": [],
                    "timeShift": null,
                    "title": "API Request Rate",
                    "tooltip": {
                      "shared": true,
                      "sort": 0,
                      "value_type": "individual"
                    },
                    "type": "graph",
                    "xaxis": {
                      "buckets": null,
                      "mode": "time",
                      "name": null,
                      "show": true,
                      "values": []
                    },
                    "yaxes": [
                      {
                        "format": "short",
                        "label": null,
                        "logBase": 1,
                        "max": null,
                        "min": null,
                        "show": true
                      },
                      {
                        "format": "short",
                        "label": null,
                        "logBase": 1,
                        "max": null,
                        "min": null,
                        "show": true
                      }
                    ],
                    "yaxis": {
                      "align": false,
                      "alignLevel": null
                    }
                  },
                  {
                    "aliasColors": {},
                    "bars": false,
                    "dashLength": 10,
                    "dashes": false,
                    "datasource": "Prometheus",
                    "fieldConfig": {
                      "defaults": {
                        "custom": {}
                      },
                      "overrides": []
                    },
                    "fill": 1,
                    "fillGradient": 0,
                    "gridPos": {
                      "h": 8,
                      "w": 12,
                      "x": 12,
                      "y": 0
                    },
                    "hiddenSeries": false,
                    "id": 3,
                    "legend": {
                      "avg": false,
                      "current": false,
                      "max": false,
                      "min": false,
                      "show": true,
                      "total": false,
                      "values": false
                    },
                    "lines": true,
                    "linewidth": 1,
                    "nullPointMode": "null",
                    "options": {
                      "alertThreshold": true
                    },
                    "percentage": false,
                    "pluginVersion": "7.2.0",
                    "pointradius": 2,
                    "points": false,
                    "renderer": "flot",
                    "seriesOverrides": [],
                    "spaceLength": 10,
                    "stack": false,
                    "steppedLine": false,
                    "targets": [
                      {
                        "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"maily-api\"}[5m])) by (le, endpoint))",
                        "interval": "",
                        "legendFormat": "{{endpoint}}",
                        "refId": "A"
                      }
                    ],
                    "thresholds": [],
                    "timeFrom": null,
                    "timeRegions": [],
                    "timeShift": null,
                    "title": "API Request Duration (p95)",
                    "tooltip": {
                      "shared": true,
                      "sort": 0,
                      "value_type": "individual"
                    },
                    "type": "graph",
                    "xaxis": {
                      "buckets": null,
                      "mode": "time",
                      "name": null,
                      "show": true,
                      "values": []
                    },
                    "yaxes": [
                      {
                        "format": "s",
                        "label": null,
                        "logBase": 1,
                        "max": null,
                        "min": null,
                        "show": true
                      },
                      {
                        "format": "short",
                        "label": null,
                        "logBase": 1,
                        "max": null,
                        "min": null,
                        "show": true
                      }
                    ],
                    "yaxis": {
                      "align": false,
                      "alignLevel": null
                    }
                  }
                ],
                "refresh": "10s",
                "schemaVersion": 26,
                "style": "dark",
                "tags": [],
                "templating": {
                  "list": []
                },
                "time": {
                  "from": "now-6h",
                  "to": "now"
                },
                "timepicker": {},
                "timezone": "",
                "title": "Maily API Dashboard",
                "uid": "maily-api",
                "version": 1
              }
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy
          isDefault: false
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
    kubeApiServer:
      enabled: true
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: true
    coreDns:
      enabled: true
    kubeEtcd:
      enabled: true
    kubeScheduler:
      enabled: true
    kubeProxy:
      enabled: true
