apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-rotation
  namespace: maily-production
spec:
  schedule: "0 0 * * 0"  # Weekly on Sunday at midnight
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: vault-auth
          containers:
          - name: secret-rotation
            image: hashicorp/vault:1.15.2
            command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache curl jq kubectl bash
              cp /scripts/secret-rotation.sh /tmp/
              chmod +x /tmp/secret-rotation.sh
              export VAULT_TOKEN=$(cat /vault/token/token)
              /tmp/secret-rotation.sh
            env:
            - name: VAULT_ADDR
              value: "https://vault.vault.svc.cluster.local:8200"
            - name: KUBERNETES_NAMESPACE
              value: "maily-production"
            - name: ROTATION_LOG_FILE
              value: "/logs/secret-rotation.log"
            - name: ROTATION_MODE
              value: "all"
            volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
            - name: logs-volume
              mountPath: /logs
            - name: vault-token
              mountPath: /vault/token
              readOnly: true
          volumes:
          - name: scripts-volume
            configMap:
              name: secret-rotation-scripts
              defaultMode: 0755
          - name: logs-volume
            persistentVolumeClaim:
              claimName: secret-rotation-logs-pvc
          - name: vault-token
            secret:
              secretName: vault-token
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-rotation-scripts
  namespace: maily-production
data:
  secret-rotation.sh: |
    #!/bin/bash
    # This content will be replaced by the actual script file
    # The script is stored as a separate file for better maintainability
    echo "Secret rotation script placeholder - use kubectl to create the ConfigMap from the actual file"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secret-rotation-logs-pvc
  namespace: maily-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: maily-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
  namespace: maily-production
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-auth-secret-manager
  namespace: maily-production
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: maily-production
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
