apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-mesh
  namespace: staging
  labels:
    app: ai-mesh
    component: ai-service
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-mesh
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ai-mesh
        component: ai-service
        environment: staging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: ai-mesh
        image: justmaily/ai-mesh-network:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: ENVIRONMENT
          value: "staging"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: staging-secrets
              key: redis-url
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: staging-database-config
              key: host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: staging-database-config
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: staging-database-config
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: staging-database-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: staging-database-credentials
              key: password
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: staging-llm-api-keys
              key: anthropic
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: staging-llm-api-keys
              key: openai
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: staging-llm-api-keys
              key: google
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-mesh
  namespace: staging
  labels:
    app: ai-mesh
    component: ai-service
    environment: staging
spec:
  selector:
    app: ai-mesh
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-mesh
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-mesh
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-mesh
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - ai-mesh-staging.justmaily.com
    secretName: ai-mesh-staging-tls
  rules:
  - host: ai-mesh-staging.justmaily.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ai-mesh
            port:
              name: http