apiVersion: v1
kind: Service
metadata:
  name: email-processing-service
  namespace: maily-production
  labels:
    app: email-processing-service
    service: email
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  selector:
    app: email-processing-service
  ports:
  - port: 80
    targetPort: 3000
    name: http
  type: ClusterIP
