global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/alert.rules"
  - "rules/recording.rules"

scrape_configs:
  - job_name: 'maily-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'maily-backend'

  - job_name: 'maily-frontend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['frontend:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'maily-frontend'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'maily-redis'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'maily-postgres'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'maily-node'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'maily-cadvisor'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.justmaily.com/health
        - https://justmaily.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
