apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maily
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maily/maily.git
    targetRevision: HEAD
    path: infrastructure/kubernetes/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: maily
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
