#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format staged files
npx lint-staged

# Run typescript check
npm run typecheck

# Run Python linters for Python files
if git diff --cached --name-only | grep -E '\.py$'; then
  # Run Python linters
  find apps -type f -name "*.py" | xargs python -m black --check
  find apps -type f -name "*.py" | xargs python -m ruff check
fi