apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: default
data:
  pgbouncer.ini: |
    [databases]
    * = host=postgres-primary.default.svc.cluster.local port=5432

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 6432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 10000
    default_pool_size = 100
    min_pool_size = 10
    reserve_pool_size = 10
    reserve_pool_timeout = 5
    server_reset_query = DISCARD ALL
    server_check_query = select 1
    server_check_delay = 30
    server_lifetime = 3600
    server_idle_timeout = 600
    client_idle_timeout = 600
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    stats_period = 60
    ignore_startup_parameters = extra_float_digits
    tcp_keepalive = 1
    tcp_keepidle = 60
    tcp_keepintvl = 30
    tcp_keepcnt = 5
    tcp_user_timeout = 0
    application_name_add_host = 1
    admin_users = postgres

  userlist.txt: |
    "postgres" "md5password"
    "maily_user" "md5password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: default
  labels:
    app: pgbouncer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pgbouncer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: edoburu/pgbouncer:1.18.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6432
          name: pgbouncer
        - containerPort: 6433
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: PGBOUNCER_STATS_USERS
          value: postgres
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        volumeMounts:
        - name: pgbouncer-config
          mountPath: /etc/pgbouncer
        livenessProbe:
          tcpSocket:
            port: pgbouncer
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: pgbouncer
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: pgbouncer-config
        configMap:
          name: pgbouncer-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: default
  labels:
    app: pgbouncer
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "6433"
spec:
  selector:
    app: pgbouncer
  ports:
  - name: pgbouncer
    port: 6432
    targetPort: pgbouncer
  - name: metrics
    port: 6433
    targetPort: metrics
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: pgbouncer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pgbouncer-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pgbouncer
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pgbouncer-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: pgbouncer
  endpoints:
  - port: metrics
    interval: 15s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cGFzc3dvcmQ=  # password
