apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.maily.example.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "maily-role"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: maily-external-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: maily-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-url
    remoteRef:
      key: maily/database
      property: url
  - secretKey: redis-url
    remoteRef:
      key: maily/redis
      property: url
  - secretKey: rabbitmq-url
    remoteRef:
      key: maily/rabbitmq
      property: url
  - secretKey: jwt-secret
    remoteRef:
      key: maily/jwt
      property: secret
  - secretKey: postgres-user
    remoteRef:
      key: maily/database
      property: username
  - secretKey: postgres-password
    remoteRef:
      key: maily/database
      property: password
  - secretKey: rabbitmq-user
    remoteRef:
      key: maily/rabbitmq
      property: username
  - secretKey: rabbitmq-password
    remoteRef:
      key: maily/rabbitmq
      property: password
  - secretKey: openai-api-key
    remoteRef:
      key: maily/ai
      property: openai-key
  - secretKey: anthropic-api-key
    remoteRef:
      key: maily/ai
      property: anthropic-key
  - secretKey: google-api-key
    remoteRef:
      key: maily/ai
      property: google-key
