apiVersion: v1
kind: Secret
metadata:
  name: maily-secrets
type: Opaque
data:
  # These are placeholders and should be replaced with actual base64-encoded values
  database-url: {{ PAGERDUTY_SERVICE_KEY }}{{ PAGERDUTY_SERVICE_KEY }}MzIvbWFpbHk=
  redis-url: {{ PAGERDUTY_SERVICE_KEY }}LzA=
  rabbitmq-url: {{ PAGERDUTY_SERVICE_KEY }}aWx5LXJhYmJpdG1xOjU2NzIv
  jwt-secret: Y2hhbmdlbWVfaW5fcHJvZHVjdGlvbg==
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  rabbitmq-user: bWFpbHk=
  rabbitmq-password: cGFzc3dvcmQ=
  openai-api-key: eW91ci1vcGVuYWktYXBpLWtleQ==
  anthropic-api-key: eW91ci1hbnRocm9waWMtYXBpLWtleQ==
  google-api-key: eW91ci1nb29nbGUtYXBpLWtleQ==
